trigger: 
- none

pool:
  name: Azure Pipelines
  
variables:
  projectName: WeatherForecast

stages:
- stage: CI
  displayName: CI
  jobs:
  - job: build
    displayName: Build stage
    steps:
    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeeded()

- stage: DeployToDev
  displayName: Dev
  jobs:
  - deployment: deploymentJob
    displayName: Deployment job
    environment:
      name: Dev
      resourceType: VirtualMachine
    variables:
      ConnectionStrings.DefaultConnection: $(devConnectionString)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'dev.$(projectName)'
              websitePhysicalPath: '%SystemDrive%\Sites\dev.$(projectName)'
              AddBinding: true
              bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"www.dev.$(projectName).pt","sslThumbprint":"","sniFlag":false}]}'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'dev.$(projectName)'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: 'dev.$(projectName)'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'dev.$(projectName)'
              Package: '$(pipeline.workspace)\**\$(projectName).zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              JSONFiles: '**/appsettings.json'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'dev.$(projectName)'

- stage: DeployToQA
  displayName: QA
  jobs:
  - deployment: deploymentJob
    displayName: Deployment job
    environment:
      name: QA
      resourceType: VirtualMachine
    variables:
      ConnectionStrings.DefaultConnection: $(qaConnectionString)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: 'qa.$(projectName)'
              websitePhysicalPath: '%SystemDrive%\Sites\qa.$(projectName)'
              AddBinding: true
              bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"www.qa.$(projectName).pt","sslThumbprint":"","sniFlag":false}]}'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: 'qa.$(projectName)'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: 'qa.$(projectName)'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: 'qa.$(projectName)'
              Package: '$(pipeline.workspace)\**\$(projectName).zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
              JSONFiles: '**/appsettings.json'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: 'qa.$(projectName)'
              
- stage: DeployToProd
  displayName: Prod
  jobs:
  - deployment: deploymentJob
    displayName: Deployment job
    environment:
      name: Prod
      resourceType: VirtualMachine
    variables:
      ConnectionStrings.DefaultConnection: $(prodConnectionString)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'CreateOrUpdateWebsite'
              WebsiteName: '$(projectName)'
              websitePhysicalPath: '%SystemDrive%\Sites\$(projectName)'
              AddBinding: true
              bindings: '{"bindings":[{"protocol":"http","ipAddress":"All Unassigned","port":"80","hostname":"www.$(projectName).pt","sslThumbprint":"","sniFlag":false}]}'
              WebsitePhysicalPathAuth: 'WebsiteUserPassThrough'
              CreateOrUpdateAppPoolForWebsite: true
              AppPoolNameForWebsite: '$(projectName)'
              DotNetVersionForWebsite: 'v4.0'
              PipeLineModeForWebsite: 'Integrated'
              AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StopWebsite'
              StartStopWebsiteName: '$(projectName)'
          - task: IISWebAppDeploymentOnMachineGroup@0
            inputs:
              WebSiteName: '$(projectName)'
              Package: '$(pipeline.workspace)\**\$(projectName).zip'
              RemoveAdditionalFilesFlag: true
              TakeAppOfflineFlag: true
          - task: IISWebAppManagementOnMachineGroup@0
            inputs:
              IISDeploymentType: 'IISWebsite'
              ActionIISWebsite: 'StartWebsite'
              StartStopWebsiteName: '$(projectName)'